FROM golang:1.25.5 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/node ./cmd/node

FROM alpine:3.20
WORKDIR /app

RUN adduser -D appuser
USER appuser

COPY --from=builder /bin/node /app/node

EXPOSE 8080
ENTRYPOINT ["/app/node"]